title: Research Retreat 2025
preposition: ''
description: >-
  "Exploring new generative AI methods for understanding dynamic complex social and socio-ecological systems” 
  
  9th – 13th June 2025 
  
  in Brussels (Double Tree By Hilton Brussels City Hotel, Rue Gineste 3, 1210 Brussels)
baseurl: "/genai2025rr" # the subpath of your site, e.g. /blog
url: "https://ajaymanivannan.github.io" # the base hostname & protocol for your site, e.g. https://example.com

# Build settings
markdown: kramdown
sass:
  style: compressed

# Exclude from processing
exclude:
  - vendor
  - .github/
  - README.md
  - LICENSE.md
  - REDISTRIBUTED.md
  - purgecss.config.js

# Collections and their defaults
collections:
  talks:
    output: true
    permalink: /:collection/:title/
  speakers:
    output: true
    permalink: /:collection/:title/
  rooms:
    output: true
    permalink: /:collection/:title/

defaults:
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: ""
      type: speakers
    values:
      layout: speaker
  - scope:
      path: ""
      type: rooms
    values:
      layout: room

conference:

  # Language
  lang: en

  # Timezone
  tz: "+02:00"

  # Show theme errors:
  show_errors: True

  # Navigation bar
  navigation:
    logo:
      name: Home
      # img: ''
      url: ''
    breakpoint: md
    links:
      - name: Program
        relative_url: /program/
      - name: Talks
        relative_url: /talks/
      - name: Speakers
        relative_url: /speakers/
      - name: Location
        relative_url: /location/
      # - name: Previous Editions
      #   menu:
      #     - name: 2020 (current)
      #       disabled: true
      #     - name: 2019
      #       relative_url: /2019/
      #     - name: 2018
      #       relative_url: /2018/

  # Link Preview for Sharing
  link_preview:
    # also adapt "preposition" property at top for more meaningful descriptions
    disable: false
    img:
      twitter: 'twitter_preview.png'      # inside /assets/images/
      open_graph: 'facebook_preview.png'  # inside /assets/images/

  # Main landing page
  main:
    # logo:
    #   img: ''
    links:
      - name: Program
        relative_url: /program/
      - name: How to get there
        relative_url: /location/
      # - name: Tickets
      #   disabled: true
      #   absolute_url: ''

  # Information boxes
  info_bars:
    - title: Welcome to the 2025 Research Retreat
      color: primary
      main_only: true
      text: |
        Hello All. Work in Progress.

    - text: To display any info to be brought to attention
      color: warning
      pages_only: true

  # Live indications
  live:
    date: 09.06.2025
    timezone: GMT+1
    stop:       240  # in minutes
    streaming:
      enable: true
      pause:     60  # in minutes
      prepend:    5  # in minutes
      extend:     5  # in minutes
    demo:
      enable: false
      duration: 300  # in seconds
      pause:     10  # in seconds

  talks:
    # Talk categories
    main_categories:
      - name: Intros
        color: info
      - name: Talks
        color: success
      - name: Workshop
        color: warning
      - name: Group Discussion
        color: secondary
      - name: Breaks
        color: light
    # Hide icons on talk overview page
    hide_icons: false

  speakers:
    # Show first and last name
    show_firstname: true

  location:
    # Disable links to locations
    hide: false
    # URL of location / room overview page
    url: '/location'
    # Main page title shown on location/room navigation bar
    navbar_title: 'Location'
    # Show map on location main page.  Set `map: false` if you don't want to
    # display it.
    map:
      # Initial map center point
      home_coord: 50.855407171556195, 4.360208134714779
      # Alternative map providers can be found on https://leaflet-extras.github.io/leaflet-providers/preview/
      # The following do match the Bootstrap design not too badly:
      #   - Thunderforest.Neighbourhood
      #   - Esri.WorldTopoMap
      map_provider: "OpenStreetMap.Mapnik"
      default_zoom: 17


  program:
    # URL of program page
    url: '/program'

    # Time steps in program table
    time_steps: 30 # in minutes

    # Show intermediary time steps (next to full hours)
    show_alltimes: true
